#!/bin/bash
# Generate comic pages from images in assets/img/leonine/
# Run this script from the repo root whenever you add/remove images.
#
# Safety: existing pages are never overwritten — only missing frontmatter
# fields such as description or next_page are inserted, and new pages are
# created. The shared page list lives in _data/leonine_pages.yml.
#
# New images must sort after all existing ones — if an image would be
# inserted in the middle, the script aborts with an explanation.

set -euo pipefail

COMIC_DIR="comics"
IMG_DIR="assets/img/leonine"
PAGES_DATA="_data/leonine_pages.yml"

mapfile -t images < <(ls "$IMG_DIR"/ | grep -iE '\.(png|jpg|jpeg|webp|gif)$' | sort -t_ -k1 -n)

total=${#images[@]}

if [ "$total" -eq 0 ]; then
  echo "No images found in $IMG_DIR"
  exit 1
fi

pad_width=2
if [ "$total" -gt 100 ]; then
  pad_width=3
fi

page_slug() {
  printf "%0${pad_width}d" "$1"
}

comic_description() {
  if [ "$1" -eq 0 ]; then
    echo "The cover page of the Leonine webcomic archive."
  else
    echo "Page $1 of the Leonine webcomic archive."
  fi
}

mapfile -t existing < <(
  if [ -d "$COMIC_DIR" ]; then
    ls "$COMIC_DIR"/*.md 2>/dev/null | xargs -n1 basename 2>/dev/null | sed 's/\.md$//' | sort -n
  fi
)
existing_count=${#existing[@]}

for i in "${!existing[@]}"; do
  old="${existing[$i]}"
  expected="$(page_slug "$i")"
  if [ "$old" != "$expected" ]; then
    echo "ERROR: Page ordering mismatch at position $i."
    echo "  Existing page: $old.md"
    echo "  Expected: $expected.md"
    exit 1
  fi
done

for (( i=0; i<existing_count && i<total; i++ )); do
  slug="$(page_slug "$i")"
  page_file="$COMIC_DIR/$slug.md"
  if ! grep -q "^description:" "$page_file"; then
    description="$(comic_description "$i")"
    sed -i "/^title:/a description: \"$description\"" "$page_file"
  fi
done

cat > "$PAGES_DATA" <<ENDOFDATA
# Auto-generated by generate_comic.sh — do not edit manually.
ENDOFDATA
for i in "${!images[@]}"; do
  slug="$(page_slug "$i")"
  if [ "$i" -eq 0 ]; then
    label="Cover"
  else
    label="$i"
  fi
  echo "- url: \"/comics/$slug/\"" >> "$PAGES_DATA"
  echo "  label: \"$label\"" >> "$PAGES_DATA"
done

if [ "$existing_count" -gt 0 ] && [ "$total" -gt "$existing_count" ]; then
  last_idx=$((existing_count - 1))
  last_slug="$(page_slug "$last_idx")"
  last_file="$COMIC_DIR/$last_slug.md"
  next_slug="$(page_slug "$existing_count")"

  if ! grep -q "^next_page:" "$last_file"; then
    sed -i "0,/^---$/!{/^---$/ i\\
next_page: \"/comics/$next_slug/\"
}" "$last_file"
  fi
fi

new_count=0
for (( i=existing_count; i<total; i++ )); do
  img="${images[$i]}"
  key="${img%.*}"
  slug="$(page_slug "$i")"

  if [ "$i" -eq 0 ]; then
    title="Leonine — Cover"
  else
    title="Leonine — Page $i"
  fi

  prev_line=""
  next_line=""
  if [ "$i" -gt 0 ]; then
    prev_line="prev_page: \"/comics/$(page_slug $((i-1)))/\""
  fi
  if [ "$i" -lt $((total - 1)) ]; then
    next_line="next_page: \"/comics/$(page_slug $((i+1)))/\""
  fi

  mkdir -p "$COMIC_DIR"

  cat > "$COMIC_DIR/$slug.md" <<ENDOFPAGE
---
layout: comic
title: "$title"
description: "$(comic_description "$i")"
image: "$img"
image_key: "$key"
page_num: $i
permalink: "/comics/$slug/"
${prev_line}
${next_line}
---
ENDOFPAGE

  new_count=$((new_count + 1))
done

echo "Done: $total total pages ($existing_count existing, $new_count new)"
